org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.107
loader_version_range=[1,)

mod_id=mobflowutilities
mod_name=Mob Flow Utilities
mod_license=MIT
mod_version=3.2.1.7-mc-26.1.2
mod_group_id=com.misterd.mobflowutilities
mod_authors=MisterD Modding
mod_description=A mob farming automation mod.
